Insert into skills_collector.sources (description, name) values('szkoła w Starych Jabłonkach', 'szkoła');
Insert into skills_collector.sources (description, name) values('strony informacyjne', 'internet');
Insert into skills_collector.sources (description, name) values('Biblioteka nr 4', 'biblioteka');
Insert into skills_collector.sources (description, name) values('Ślepa ulica', 'ulica');
Insert into skills_collector.sources (description, name) values('bliższa i dalsza', 'rodzina');
Insert into skills_collector.sources (description, name) values('gry przygodowe', 'gry komputerowe');
Insert into skills_collector.sources (description, name) values('telewizja publiczna', 'telewizja');

Insert into skills_collector.skills(name) values('czytanie wspak');
Insert into skills_collector.skills(name) values('biegania do tyłu na plecach');
Insert into skills_collector.skills(name) values('krytyczne myślenie');
Insert into skills_collector.skills(name) values('retoryka polityczna');
Insert into skills_collector.skills(name) values('władanie mieczem świetlnym');
Insert into skills_collector.skills(name) values('obsługa automatu z jeżykami');
Insert into skills_collector.skills(name) values('rozpoznawanie twarzy');
Insert into skills_collector.skills(name) values('wymijanie kropli deszczu');
Insert into skills_collector.skills(name) values('trawienie trawy');
Insert into skills_collector.skills(name) values('generowanie owłosienia');
Insert into skills_collector.skills(name) values('blokowanie katabolizmu mięśniowego');

Insert into skills_collector.sources_attached_skills(SOURCE_ID, SKILL_ID) values(1, 2);
Insert into skills_collector.sources_attached_skills(SOURCE_ID, SKILL_ID) values(1, 5);
Insert into skills_collector.sources_attached_skills(SOURCE_ID, SKILL_ID) values(1, 6);
Insert into skills_collector.sources_attached_skills(SOURCE_ID, SKILL_ID) values(2, 3);
Insert into skills_collector.sources_attached_skills(SOURCE_ID, SKILL_ID) values(2, 4);
Insert into skills_collector.sources_attached_skills(SOURCE_ID, SKILL_ID) values(2, 5);
Insert into skills_collector.sources_attached_skills(SOURCE_ID, SKILL_ID) values(2, 1);
Insert into skills_collector.sources_attached_skills(SOURCE_ID, SKILL_ID) values(3, 7);
Insert into skills_collector.sources_attached_skills(SOURCE_ID, SKILL_ID) values(3, 11);
Insert into skills_collector.sources_attached_skills(SOURCE_ID, SKILL_ID) values(3, 9);
Insert into skills_collector.sources_attached_skills(SOURCE_ID, SKILL_ID) values(4, 8);
Insert into skills_collector.sources_attached_skills(SOURCE_ID, SKILL_ID) values(4, 10);
Insert into skills_collector.sources_attached_skills(SOURCE_ID, SKILL_ID) values(5, 1);
Insert into skills_collector.sources_attached_skills(SOURCE_ID, SKILL_ID) values(5, 3);
Insert into skills_collector.sources_attached_skills(SOURCE_ID, SKILL_ID) values(5, 7);
Insert into skills_collector.sources_attached_skills(SOURCE_ID, SKILL_ID) values(6, 5);
Insert into skills_collector.sources_attached_skills(SOURCE_ID, SKILL_ID) values(6, 6);
Insert into skills_collector.sources_attached_skills(SOURCE_ID, SKILL_ID) values(7, 3);
Insert into skills_collector.sources_attached_skills(SOURCE_ID, SKILL_ID) values(7, 6);
Insert into skills_collector.sources_attached_skills(SOURCE_ID, SKILL_ID) values(7, 8);
Insert into skills_collector.sources_attached_skills(SOURCE_ID, SKILL_ID) values(7, 9);